image: registry.gitlab.com/remipassmoilesel/abc-map-2/build-image:0.1

cache:
  paths:
    - backend/node_modules/
    - frontend/node_modules/

test:
  script:
    - ./packages/infrastructure/scripts/ci.sh
