image: registry.gitlab.com/remipassmoilesel/abc-map-2/build-image:0.1

variables:
  CI: "true"

cache:
  paths:
    - packages/backend/node_modules/
    - packages/frontend/node_modules/

test:
  script:
    - packages/infrastructure/cli/main.js ci
