image: registry.gitlab.com/remipassmoilesel/abc-map-2/build-image:0.2

variables:
  CI: "true"
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: admin
  ABC_CONFIGURATION: "resources/configuration/test.js"

services:
  - mongo:4.2-bionic

cache:
  key: main
  paths:
    - packages/backend/node_modules/
    - packages/frontend/node_modules/

test:
  # WARNING: do not release cypress screenshots as artifacts, otherwise test credentials can be leaked
  script:
    - ./abc-cli ci

