---
image: registry.gitlab.com/remipassmoilesel/abc-map-2/build-image:0.2

variables:
  CI: "true"
  ABC_CONFIGURATION: "resources/configuration/test.js"
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/.yarn-cache"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/.cypress-cache"
  NODE_OPTIONS: "--max-old-space-size=3500"

cache:
  key: main
  paths:
    - .yarn-cache
    - .cypress-cache
    - packages/abc-cli/node_modules
    - packages/backend/node_modules/
    - packages/documentation/node_modules/
    - packages/e2e-tests/node_modules/
    - packages/frontend/node_modules/
    - packages/frontend-commons/node_modules/
    - packages/performance-tests/node_modules/
    - packages/shared-entities/node_modules/


test:
  script:
    - ./abc-cli ci
  services:
    - name: mongo:4.2-bionic
      alias: mongodb
  variables:
    MONGO_INITDB_ROOT_USERNAME: admin
    MONGO_INITDB_ROOT_PASSWORD: admin
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - "packages/e2e-tests/screenshots"
