---
image: registry.gitlab.com/abc-map/abc-map-2_private/build-image:v0.7


cache:
  key: main
  paths:
    - .yarn-cache
    - .cypress-cache
    - packages/abc-cli/node_modules
    - packages/backend/node_modules/
    - packages/documentation/node_modules/
    - packages/e2e-tests/node_modules/
    - packages/frontend/node_modules/
    - packages/frontend-commons/node_modules/
    - packages/performance-tests/node_modules/
    - packages/shared-entities/node_modules/


test:
  script:
    - source ci-env.sh
    - ./abc-cli ci
  services:
    - name: mongo:4.2-bionic
      alias: mongodb
  variables:
    MONGO_INITDB_ROOT_USERNAME: admin
    MONGO_INITDB_ROOT_PASSWORD: admin
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - "packages/e2e-tests/screenshots"
