{{- if .Values.mongodb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "abc-map.fullname" . }}-mongodb
  labels:
    {{- include "abc-map.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    app.kubernetes.io/name: {{ include "abc-map.name" . }}-mongodb
    app.kubernetes.io/instance: {{ .Release.Name }}-mongodb
  {{- end }}
