apiVersion: v1
kind: Service
metadata:
  name: {{ include "abc-map.fullname" . }}-server
  labels:
    {{- include "abc-map.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.abcMap.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "abc-map.name" . }}-server
    app.kubernetes.io/instance: {{ .Release.Name }}-server
