apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "abc-map.fullname" . }}-server-config
  labels:
    {{- include "abc-map.labels" . | nindent 4 }}
data:
  config.js: |
{{ .Values.abcMap.config | indent 4 }}
