{{- if .Values.smtp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "abc-map.fullname" . }}-smtp
  labels:
  {{- include "abc-map.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.smtp.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "abc-map.name" . }}-smtp
      app.kubernetes.io/instance: {{ .Release.Name }}-smtp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "abc-map.name" . }}-smtp
        app.kubernetes.io/instance: {{ .Release.Name }}-smtp
    spec:
      containers:
        - name: smtp
          image: "mwader/postfix-relay:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: smtp
              containerPort: 25
              protocol: TCP
          env:
            - name: OPENDKIM_DOMAINS
              value: {{ .Values.smtp.dkim.domain }}={{ .Values.smtp.dkim.selector }}
            - name: POSTFIX_myhostname
              value: {{ .Values.smtp.dkim.domain }}
          lifecycle:
            postStart:
              exec:
                # This command is a workaround for read only secrets, as opendkim needs specific permissions on key
                command: ["/bin/sh", "-c", "cp /etc/opendkim/keys/{{ .Values.smtp.dkim.domain }}/{{ .Values.smtp.dkim.selector }}.private.original /etc/opendkim/keys/{{ .Values.smtp.dkim.domain }}/{{ .Values.smtp.dkim.selector }}.private"]
          livenessProbe:
            # We do not perform a TCP check in order to keep logs clean
            exec:
              command:
                - postfix
                - status
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            # We do not perform a TCP check in order to keep logs clean
            exec:
              command:
                - postfix
                - status
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2

          resources:
          {{- toYaml .Values.smtp.resources | nindent 12 }}

          volumeMounts:
            - name: private-key
              mountPath: /etc/opendkim/keys/{{ .Values.smtp.dkim.domain }}/{{ .Values.smtp.dkim.selector }}.private.original
              subPath: {{ .Values.smtp.dkim.selector }}.private.original

      volumes:
        - name: private-key
          configMap:
            name: {{ include "abc-map.fullname" . }}-smtp-config
            items:
              - key: private-key
                path: {{ .Values.smtp.dkim.selector }}.private.original
                mode: 500

      {{- with .Values.smtp.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.smtp.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.smtp.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
  {{- end }}

  {{- end }}
