storage: /tmp/verdaccio-storage
listen: localhost:4873
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "@abc-map/*":
    access: $all
    publish: $all
    proxy: npmjs
  "**":
    access: $all
    publish: $authenticated
    proxy: npmjs
middlewares:
  audit:
    enabled: false
