version: '3'

services:
  abc-mongodb:
    image: 'mongo:4.2-bionic'
    container_name: abc-mongodb
    restart: always
    ports:
      - '27019:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - 'mongodb_data:/data/db'

  abc-mongo-express:
    image: 'mongo-express:0.54'
    container_name: abc-mongo-express
    restart: always
    ports:
      - '27020:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: abc-mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27019

volumes:
  mongodb_data:
    driver: local
