version: 0.0.1
artefact:
  name:
    - language: fr
      text: Positron
    - language: en
      text: Positron
  type: basemap
  description:
    - language: fr
      text: Fond de carte basé sur OpenStreetMap, avec des couleurs claires.
    - language: en
      text: Basemap based on OpenStreetMap, with light colors.
  keywords:
    - language: fr
      text:
        - openstreetmap
    - language: en
      text:
        - openstreetmap
  provider: Carto.com
  link: https://carto.com/basemaps/
  license: LICENSE.txt
  attributions:
    - Map tiles by Carto, under CC BY 3.0. Data by OpenStreetMap, under ODbL.
  files:
    - definition.xyz
  previews:
    - preview-0.png
    - preview-1.png
    - preview-2.png
  weight: 120
