# Copyright © 2021 Rémi Pace.
# This file is part of Abc-Map.
#
# Abc-Map is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Abc-Map is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General
# Public License along with Abc-Map. If not, see <https://www.gnu.org/licenses/>.

# Default values for abc-map.

nameOverride: ""
fullnameOverride: ""

abcMap:
  replicaCount: 2
  image:
    repository: registry.gitlab.com/abc-map/abc-map-2/server
    pullPolicy: IfNotPresent
    tag: "0.1.0"

  config: |
    module.exports = {
      environmentName: 'production',
      externalUrl: 'https://<CHANGE_ME>',
      server: {
        host: '0.0.0.0',
        port: 80,
        log: {
          requests: false,
          errors: false,
        },
        // Beware of NATs, for examples in schools several clients share the same ip address
        globalRateLimit: {
          max: 1000,
          timeWindow: '30m',
        },
        authenticationRateLimit: {
          max: 200,
          timeWindow: '30m',
        },
      },
      project: {
        maxPerUser: 10,
      },
      database: {
        url: 'mongodb://<CHANGE_ME>:27017',
        username: '<CHANGE_ME>',
        password: '<CHANGE_ME>',
      },
      jwt: {
        algorithm: 'HS512',
      },
      authentication: {
        secret: '<CHANGE_ME>',
        tokenExpiresIn: '45min',
        passwordLostExpiresIn: '30min',
      },
      registration: {
        passwordSalt: '<CHANGE_ME>',
        secret: '<CHANGE_ME>',
        confirmationExpiresIn: '24h',
      },
      smtp: {
        from: 'no-reply@abc-map.fr',
        host: '<CHANGE_ME>',
        port: 25,
        auth: {
          user: '<CHANGE_ME>',
          pass: '<CHANGE_ME>',
        },
      },
      datastore: {
        path: '/srv/datastore',
      },
    };

  service:
    port: 80

  datastore:
    existingClaim: '<CHANGE_ME>'
    mountPath: /srv/datastore

  ingress:
    enabled: false
    host: <CHANGE_ME>
    annotations: { }
    tls:
      enabled: false
      secretName: <CHANGE_ME>
      host: <CHANGE_ME>

  podAnnotations: { }
  imagePullSecrets: [ ]
  resources: { }
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }


mongodb:
  enabled: true
  auth:
    rootUsername: '<CHANGE_ME>'
    rootPassword: '<CHANGE_ME>'
  persistence:
    existingClaim: <CHANGE_ME>

  resources: { }
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }


smtp:
  enabled: true
  replicaCount: 1
  dkim:
    domain: <CHANGE_ME>
    selector: <CHANGE_ME>
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      <CHANGE_ME>


  resources: { }
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

